openapi: 3.0.0
info:
  title: API Asistente - Cognitiva
  version: '0.1'
  description: "Esta documentación hace referencia a API's que son utilizadas por clientes para integrarse con Cognitiva para hacer uso del Asistente Cognitivo.\nLa referencia aquí expuesta es para clientes que cuentan con una API Key entregada por Cognitiva para el uso de las API's . \n"
  contact:
    name: Soporte Chile
    url: 'https://cognitivacl.zendesk.com/'
    email: soporte_chile@cognitiva.la
servers:
  - url: 'https://ambiente-cliente.mycognitiva.io/mad'
paths:
  /external_message:
    parameters: []
    post:
      summary: Enviar mensaje
      description: Recibe mensaje desde integración WhatsApp para ser respondido por Asistente Cognitivo.
      security:
        - API Key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cid:
                  description: ID de Conversation
                  type: string
                id_cliente:
                  type: string
                  description: ID de cliente.
                location:
                  type: string
                  description: En desuso
                from_message:
                  type: string
                  description: Teléfono / correo / usuario emisor de mensaje.
                to_message:
                  type: string
                  description: Teléfono / correo / usuario receptor de mensaje.
                body_message:
                  type: string
                  description: Texto que será entregado a Asistente Cognitivo.
                datetime:
                  type: string
                  description: Marca de tiempo para fines estadísticos.
              required:
                - cid
                - id_cliente
                - from_message
                - to_message
                - body_message
            examples:
              Ejemplo:
                value:
                  cid: null
                  id_cliente: '1'
                  location: ''
                  msg: 'Hola, estoy resfriado, necesito ayuda, qué me recomiendas?'
                  token: ''
        description: Parámetros necesarios para derivar mensaje a Asistente.
      parameters: []
      responses:
        '200':
          description: |
            Respuesta estándar cuando un mensaje es recibido y entregado a asistente Cognitivo.
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  estado:
                    type: object
                    properties:
                      codigoEstado:
                        type: number
                      glosaEstado:
                        type: string
                  general:
                    type: object
                    properties:
                      cid:
                        type: string
                      region:
                        type: string
                      tipo:
                        type: string
                  msg:
                    type: array
                    items: {}
              examples:
                Ejemplo:
                  value:
                    estado:
                      codigoEstado: 200
                      glosaEstado: ok
                    general:
                      cid: ad145638-c22c-4963-b7b9-b7cxvebb5
                      nodo_id:
                        _node_output_map:
                          Bienvenido:
                            '0':
                              - 2
                          En otras cosas:
                            '0':
                              - 0
                          node_2_156536dsd18903:
                            '0':
                              - 0
                          node_3_1565288531030:
                            '0':
                              - 0
                          node_6_1567700307757:
                            '0':
                              - 0
                          node_8_1565209978082:
                            '0':
                              - 0
                          response_8_1567700728787:
                            '0':
                              - 0
                        branch_exited: true
                        branch_exited_reason: completed
                        dialog_request_counter: 8
                        dialog_stack:
                          - dialog_node: root
                        dialog_turn_counter: 8
                        initialized: true
                      tipo: ''
                    like: false
                    msg:
                      - 'Ok, pero antes debo hacerte algunas preguntas. '
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                Ejemplo:
                  value:
                    response: 'Request con error. '
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                Response:
                  value:
                    response: 'No autorizado para la request. '
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                Response:
                  value:
                    response: 'Request no encontrado. '
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                Response:
                  value:
                    response: 'Error en el servidor. '
        '':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    msg:
                      type: array
                      items: {}
                    general:
                      type: array
                      items:
                        type: object
                        properties:
                          cid:
                            type: string
                          region:
                            type: string
                          tipo:
                            type: string
                    estado:
                      type: object
                      properties:
                        codigoEstado:
                          type: number
                        glosaEstado:
                          type: string
      operationId: Enviar mensaje a Asistente
components:
  schemas: {}
  securitySchemes:
    API Key:
      name: API Key
      type: apiKey
      in: query
      description: API Key proporcionada por Cognitiva para hacer uso de los endpoints públicos.
